### ISSUE TITLE
Reasons why we're not using this on React Native

### ISSUE THREAD

**Issue by vjeux** [torifat/babel-plugin-react-native-css-shorthand#1]
I've actually implemented this originally but backed it off. Some thoughts:
- A lot of people get confused by what those number means. It's not clear that '5px 6px' means 5 vertical and 6 horizontal. I still have no idea what the 3-number version is. It is surely easier to write but harder to read.
- A common use for this is to set the vertical padding and horizontal. On react native we introduced paddingHorizontal and paddingVertical for this.
- We tweaked the merging behavior to be that the most specific wins (instead of the last defined wins in css). So you can do paddingLeft: 10, padding: 20 which is going to have everything at 20 except for left with 10.

**Comment by torifat** [comment]
Thank you so much for your thoughts :smiley:. May I add :point_up_2: to a `Reasons why this isn't in the core` section?

**Comment by vjeux** [comment]
Sure :)

**Comment by torifat** [comment]
Added :smile: Thanks :heart:
